slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: localization            # <-- relocalisation continue sur la posegraph
    map_file_name: ""             # écrasé par le launch (arg map_file)

    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    map_update_interval: 2.0
    publish_period: 0.02
    transform_publish_period: 0.02

    use_scan_matching: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.174

    # en localization, la pose initiale vient du paramètre ou de /initialpose
    # (bouton "2D Pose Estimate" de RViz publie sur /initialpose)
